# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'garvax' do

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  ]
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  target 'garvax-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'garvaxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'garvax-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # Pods for garvax-tvOS

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == 'yoga'
      target.remove_from_project
      target.build_configurations.each do |config|
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
      end
    end
  end
end
